# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ep_ICRT_em <- function(EL, ER, S, tmax, breaks, iter) {
    .Call(`_NPMLEDIC_ep_ICRT_em`, EL, ER, S, tmax, breaks, iter)
}

ep_DICRT_em <- function(EL, ER, SL, SR, tmax, breaks, iter) {
    .Call(`_NPMLEDIC_ep_DICRT_em`, EL, ER, SL, SR, tmax, breaks, iter)
}

