# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ep_DIC_em <- function(aind_L, aind_R, ctype, alpha0, maxit, tol) {
    .Call(`_NPMLEDIC_ep_DIC_em`, aind_L, aind_R, ctype, alpha0, maxit, tol)
}

ep_DIC_vb <- function(aind_L, aind_R, ctype, alpha0, maxit, tol) {
    .Call(`_NPMLEDIC_ep_DIC_vb`, aind_L, aind_R, ctype, alpha0, maxit, tol)
}

ep_DIC_gibbs <- function(aind_L, aind_R, ctype, alpha0, iter) {
    .Call(`_NPMLEDIC_ep_DIC_gibbs`, aind_L, aind_R, ctype, alpha0, iter)
}

joint_DIC_em <- function(EL, ER, SL, SR, m, maxit, tol) {
    .Call(`_NPMLEDIC_joint_DIC_em`, EL, ER, SL, SR, m, maxit, tol)
}

