# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ep_DIC_em <- function(EL, ER, SL, SR, ctype, breaks, alpha0, iter) {
    .Call(`_NPMLEDIC_ep_DIC_em`, EL, ER, SL, SR, ctype, breaks, alpha0, iter)
}

ep_DIC_vb <- function(EL, ER, SL, SR, ctype, breaks, alpha0, iter) {
    .Call(`_NPMLEDIC_ep_DIC_vb`, EL, ER, SL, SR, ctype, breaks, alpha0, iter)
}

